//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarryFileMan.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BarryFileMan.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string AppUrl {
            get {
                return ResourceManager.GetString("AppUrl", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        public static string ConfigPath {
            get {
                return ResourceManager.GetString("ConfigPath", resourceCulture);
            }
        }
        
        public static string CopyNew {
            get {
                return ResourceManager.GetString("CopyNew", resourceCulture);
            }
        }
        
        public static string CopyOriginal {
            get {
                return ResourceManager.GetString("CopyOriginal", resourceCulture);
            }
        }
        
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        public static string DefaultLoadOption {
            get {
                return ResourceManager.GetString("DefaultLoadOption", resourceCulture);
            }
        }
        
        public static string DefaultRegexFileFilter {
            get {
                return ResourceManager.GetString("DefaultRegexFileFilter", resourceCulture);
            }
        }
        
        public static string DeleteEmptyFolders {
            get {
                return ResourceManager.GetString("DeleteEmptyFolders", resourceCulture);
            }
        }
        
        public static string DeleteEmptyFoldersDefault {
            get {
                return ResourceManager.GetString("DeleteEmptyFoldersDefault", resourceCulture);
            }
        }
        
        public static string DeleteEmptyFoldersDescription {
            get {
                return ResourceManager.GetString("DeleteEmptyFoldersDescription", resourceCulture);
            }
        }
        
        public static string DeleteExcludedFiles {
            get {
                return ResourceManager.GetString("DeleteExcludedFiles", resourceCulture);
            }
        }
        
        public static string DeleteExcludedFilesDefault {
            get {
                return ResourceManager.GetString("DeleteExcludedFilesDefault", resourceCulture);
            }
        }
        
        public static string DeleteExcludedFilesDescription {
            get {
                return ResourceManager.GetString("DeleteExcludedFilesDescription", resourceCulture);
            }
        }
        
        public static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        public static string DeletePresetPrompt {
            get {
                return ResourceManager.GetString("DeletePresetPrompt", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string DotNetRegexQuickReferenceTitle {
            get {
                return ResourceManager.GetString("DotNetRegexQuickReferenceTitle", resourceCulture);
            }
        }
        
        public static string DotNetRegexQuickReferenceUrl {
            get {
                return ResourceManager.GetString("DotNetRegexQuickReferenceUrl", resourceCulture);
            }
        }
        
        public static string DragDropFilesFolders {
            get {
                return ResourceManager.GetString("DragDropFilesFolders", resourceCulture);
            }
        }
        
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        public static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        public static string FailedToDeleteEmptyFoldersMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteEmptyFoldersMessage", resourceCulture);
            }
        }
        
        public static string FailedToDeleteExcludedFilesMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteExcludedFilesMessage", resourceCulture);
            }
        }
        
        public static string FailedToMoveFilesMessage {
            get {
                return ResourceManager.GetString("FailedToMoveFilesMessage", resourceCulture);
            }
        }
        
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        public static string FilenameAndDirectory {
            get {
                return ResourceManager.GetString("FilenameAndDirectory", resourceCulture);
            }
        }
        
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        public static string FilesFailedToRenameMessage {
            get {
                return ResourceManager.GetString("FilesFailedToRenameMessage", resourceCulture);
            }
        }
        
        public static string FilesRenamedSuccessMessage {
            get {
                return ResourceManager.GetString("FilesRenamedSuccessMessage", resourceCulture);
            }
        }
        
        public static string FindMatch {
            get {
                return ResourceManager.GetString("FindMatch", resourceCulture);
            }
        }
        
        public static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        public static string FlattenFolder {
            get {
                return ResourceManager.GetString("FlattenFolder", resourceCulture);
            }
        }
        
        public static string FlattenFolderConfirmationQuestion {
            get {
                return ResourceManager.GetString("FlattenFolderConfirmationQuestion", resourceCulture);
            }
        }
        
        public static string FlattenFolderDialogWatermark {
            get {
                return ResourceManager.GetString("FlattenFolderDialogWatermark", resourceCulture);
            }
        }
        
        public static string FlattenFolderPickerPlaceholder {
            get {
                return ResourceManager.GetString("FlattenFolderPickerPlaceholder", resourceCulture);
            }
        }
        
        public static string FlattenFolderPickerTitle {
            get {
                return ResourceManager.GetString("FlattenFolderPickerTitle", resourceCulture);
            }
        }
        
        public static string FlattenOptions {
            get {
                return ResourceManager.GetString("FlattenOptions", resourceCulture);
            }
        }
        
        public static string FlattenPageDescription {
            get {
                return ResourceManager.GetString("FlattenPageDescription", resourceCulture);
            }
        }
        
        public static string FlattenRegexFileFilterWatermark {
            get {
                return ResourceManager.GetString("FlattenRegexFileFilterWatermark", resourceCulture);
            }
        }
        
        public static string FolderFlattenedSuccessMessage {
            get {
                return ResourceManager.GetString("FolderFlattenedSuccessMessage", resourceCulture);
            }
        }
        
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        public static string FunctionAppendCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionAppendCompactDefinition", resourceCulture);
            }
        }
        
        public static string FunctionAppendCompactExample {
            get {
                return ResourceManager.GetString("FunctionAppendCompactExample", resourceCulture);
            }
        }
        
        public static string FunctionAppendDefinition {
            get {
                return ResourceManager.GetString("FunctionAppendDefinition", resourceCulture);
            }
        }
        
        public static string FunctionAppendDescription {
            get {
                return ResourceManager.GetString("FunctionAppendDescription", resourceCulture);
            }
        }
        
        public static string FunctionAppendExample {
            get {
                return ResourceManager.GetString("FunctionAppendExample", resourceCulture);
            }
        }
        
        public static string FunctionAppendParams {
            get {
                return ResourceManager.GetString("FunctionAppendParams", resourceCulture);
            }
        }
        
        public static string FunctionPadCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionPadCompactDefinition", resourceCulture);
            }
        }
        
        public static string FunctionPadCompactExample {
            get {
                return ResourceManager.GetString("FunctionPadCompactExample", resourceCulture);
            }
        }
        
        public static string FunctionPadDefinition {
            get {
                return ResourceManager.GetString("FunctionPadDefinition", resourceCulture);
            }
        }
        
        public static string FunctionPadDescription {
            get {
                return ResourceManager.GetString("FunctionPadDescription", resourceCulture);
            }
        }
        
        public static string FunctionPadExample {
            get {
                return ResourceManager.GetString("FunctionPadExample", resourceCulture);
            }
        }
        
        public static string FunctionPadParams {
            get {
                return ResourceManager.GetString("FunctionPadParams", resourceCulture);
            }
        }
        
        public static string FunctionPrependCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionPrependCompactDefinition", resourceCulture);
            }
        }
        
        public static string FunctionPrependCompactExample {
            get {
                return ResourceManager.GetString("FunctionPrependCompactExample", resourceCulture);
            }
        }
        
        public static string FunctionPrependDefinition {
            get {
                return ResourceManager.GetString("FunctionPrependDefinition", resourceCulture);
            }
        }
        
        public static string FunctionPrependDescription {
            get {
                return ResourceManager.GetString("FunctionPrependDescription", resourceCulture);
            }
        }
        
        public static string FunctionPrependExample {
            get {
                return ResourceManager.GetString("FunctionPrependExample", resourceCulture);
            }
        }
        
        public static string FunctionPrependParams {
            get {
                return ResourceManager.GetString("FunctionPrependParams", resourceCulture);
            }
        }
        
        public static string FunctionReplaceCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionReplaceCompactDefinition", resourceCulture);
            }
        }
        
        public static string FunctionReplaceCompactExample {
            get {
                return ResourceManager.GetString("FunctionReplaceCompactExample", resourceCulture);
            }
        }
        
        public static string FunctionReplaceDefinition {
            get {
                return ResourceManager.GetString("FunctionReplaceDefinition", resourceCulture);
            }
        }
        
        public static string FunctionReplaceDescription {
            get {
                return ResourceManager.GetString("FunctionReplaceDescription", resourceCulture);
            }
        }
        
        public static string FunctionReplaceExample {
            get {
                return ResourceManager.GetString("FunctionReplaceExample", resourceCulture);
            }
        }
        
        public static string FunctionReplaceParams {
            get {
                return ResourceManager.GetString("FunctionReplaceParams", resourceCulture);
            }
        }
        
        public static string FunctionTrimCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionTrimCompactDefinition", resourceCulture);
            }
        }
        
        public static string FunctionTrimCompactExample {
            get {
                return ResourceManager.GetString("FunctionTrimCompactExample", resourceCulture);
            }
        }
        
        public static string FunctionTrimDefinition {
            get {
                return ResourceManager.GetString("FunctionTrimDefinition", resourceCulture);
            }
        }
        
        public static string FunctionTrimDescription {
            get {
                return ResourceManager.GetString("FunctionTrimDescription", resourceCulture);
            }
        }
        
        public static string FunctionTrimExample {
            get {
                return ResourceManager.GetString("FunctionTrimExample", resourceCulture);
            }
        }
        
        public static string FunctionTrimParams {
            get {
                return ResourceManager.GetString("FunctionTrimParams", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string HelpRenameRegexTitle {
            get {
                return ResourceManager.GetString("HelpRenameRegexTitle", resourceCulture);
            }
        }
        
        public static string IncludeAdult {
            get {
                return ResourceManager.GetString("IncludeAdult", resourceCulture);
            }
        }
        
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        public static string InputDescription {
            get {
                return ResourceManager.GetString("InputDescription", resourceCulture);
            }
        }
        
        public static string InputOutput {
            get {
                return ResourceManager.GetString("InputOutput", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        public static string LoadFiles {
            get {
                return ResourceManager.GetString("LoadFiles", resourceCulture);
            }
        }
        
        public static string LoadFolder {
            get {
                return ResourceManager.GetString("LoadFolder", resourceCulture);
            }
        }
        
        public static string MatchGroups {
            get {
                return ResourceManager.GetString("MatchGroups", resourceCulture);
            }
        }
        
        public static string MatchGroupsDescription {
            get {
                return ResourceManager.GetString("MatchGroupsDescription", resourceCulture);
            }
        }
        
        public static string MatchPattern {
            get {
                return ResourceManager.GetString("MatchPattern", resourceCulture);
            }
        }
        
        public static string MatchPatternDescription {
            get {
                return ResourceManager.GetString("MatchPatternDescription", resourceCulture);
            }
        }
        
        public static string MatchType {
            get {
                return ResourceManager.GetString("MatchType", resourceCulture);
            }
        }
        
        public static string MatchTypeDescription {
            get {
                return ResourceManager.GetString("MatchTypeDescription", resourceCulture);
            }
        }
        
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NewNames {
            get {
                return ResourceManager.GetString("NewNames", resourceCulture);
            }
        }
        
        public static string NewPaths {
            get {
                return ResourceManager.GetString("NewPaths", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string OriginalFiles {
            get {
                return ResourceManager.GetString("OriginalFiles", resourceCulture);
            }
        }
        
        public static string OriginalPaths {
            get {
                return ResourceManager.GetString("OriginalPaths", resourceCulture);
            }
        }
        
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        public static string OutputDescription {
            get {
                return ResourceManager.GetString("OutputDescription", resourceCulture);
            }
        }
        
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        public static string PresetNameAlreadyExistsError {
            get {
                return ResourceManager.GetString("PresetNameAlreadyExistsError", resourceCulture);
            }
        }
        
        public static string PresetNameEmptyError {
            get {
                return ResourceManager.GetString("PresetNameEmptyError", resourceCulture);
            }
        }
        
        public static string PresetNamePrompt {
            get {
                return ResourceManager.GetString("PresetNamePrompt", resourceCulture);
            }
        }
        
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        public static string RegexFileFilter {
            get {
                return ResourceManager.GetString("RegexFileFilter", resourceCulture);
            }
        }
        
        public static string RegexFileFilterDescription {
            get {
                return ResourceManager.GetString("RegexFileFilterDescription", resourceCulture);
            }
        }
        
        public static string RegexFileFilterPlaceholder {
            get {
                return ResourceManager.GetString("RegexFileFilterPlaceholder", resourceCulture);
            }
        }
        
        public static string RegexRenameMatchProviderDescription {
            get {
                return ResourceManager.GetString("RegexRenameMatchProviderDescription", resourceCulture);
            }
        }
        
        public static string RegexSettings {
            get {
                return ResourceManager.GetString("RegexSettings", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        public static string RenameFilesSaveConfirmation {
            get {
                return ResourceManager.GetString("RenameFilesSaveConfirmation", resourceCulture);
            }
        }
        
        public static string RenameFilesSaveErrorsConfirmation {
            get {
                return ResourceManager.GetString("RenameFilesSaveErrorsConfirmation", resourceCulture);
            }
        }
        
        public static string RenameMatchProviders {
            get {
                return ResourceManager.GetString("RenameMatchProviders", resourceCulture);
            }
        }
        
        public static string RenamePageDescription {
            get {
                return ResourceManager.GetString("RenamePageDescription", resourceCulture);
            }
        }
        
        public static string RenamePattern {
            get {
                return ResourceManager.GetString("RenamePattern", resourceCulture);
            }
        }
        
        public static string RenamePatternDescription {
            get {
                return ResourceManager.GetString("RenamePatternDescription", resourceCulture);
            }
        }
        
        public static string RenamePatternSyntax {
            get {
                return ResourceManager.GetString("RenamePatternSyntax", resourceCulture);
            }
        }
        
        public static string RenamePatternSyntaxDescription {
            get {
                return ResourceManager.GetString("RenamePatternSyntaxDescription", resourceCulture);
            }
        }
        
        public static string RenameRegexHelpTitle {
            get {
                return ResourceManager.GetString("RenameRegexHelpTitle", resourceCulture);
            }
        }
        
        public static string RenameTMDBEpisodeDescription {
            get {
                return ResourceManager.GetString("RenameTMDBEpisodeDescription", resourceCulture);
            }
        }
        
        public static string RenameTMDBHelpTitle {
            get {
                return ResourceManager.GetString("RenameTMDBHelpTitle", resourceCulture);
            }
        }
        
        public static string RenameTMDBLanguageDescription {
            get {
                return ResourceManager.GetString("RenameTMDBLanguageDescription", resourceCulture);
            }
        }
        
        public static string RenameTMDBQueryDescription {
            get {
                return ResourceManager.GetString("RenameTMDBQueryDescription", resourceCulture);
            }
        }
        
        public static string RenameTMDBSeasonDescription {
            get {
                return ResourceManager.GetString("RenameTMDBSeasonDescription", resourceCulture);
            }
        }
        
        public static string RenameTMDBYearDescription {
            get {
                return ResourceManager.GetString("RenameTMDBYearDescription", resourceCulture);
            }
        }
        
        public static string RevertToDefault {
            get {
                return ResourceManager.GetString("RevertToDefault", resourceCulture);
            }
        }
        
        public static string RevertToDefaultConfirmationMessage {
            get {
                return ResourceManager.GetString("RevertToDefaultConfirmationMessage", resourceCulture);
            }
        }
        
        public static string RevertToDefaultErrorMessage {
            get {
                return ResourceManager.GetString("RevertToDefaultErrorMessage", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        public static string SelectCorrectMatchLabel {
            get {
                return ResourceManager.GetString("SelectCorrectMatchLabel", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SidebarExpandedDefault {
            get {
                return ResourceManager.GetString("SidebarExpandedDefault", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        public static string TagFallback {
            get {
                return ResourceManager.GetString("TagFallback", resourceCulture);
            }
        }
        
        public static string TagFallbackDescription {
            get {
                return ResourceManager.GetString("TagFallbackDescription", resourceCulture);
            }
        }
        
        public static string TagFallbackExample {
            get {
                return ResourceManager.GetString("TagFallbackExample", resourceCulture);
            }
        }
        
        public static string TagFormatFunctions {
            get {
                return ResourceManager.GetString("TagFormatFunctions", resourceCulture);
            }
        }
        
        public static string TagFormatFunctionsDescription {
            get {
                return ResourceManager.GetString("TagFormatFunctionsDescription", resourceCulture);
            }
        }
        
        public static string TagFormatFunctionsExample {
            get {
                return ResourceManager.GetString("TagFormatFunctionsExample", resourceCulture);
            }
        }
        
        public static string TagGroupIndex {
            get {
                return ResourceManager.GetString("TagGroupIndex", resourceCulture);
            }
        }
        
        public static string TagGroupIndexDescription {
            get {
                return ResourceManager.GetString("TagGroupIndexDescription", resourceCulture);
            }
        }
        
        public static string TagGroupIndexExample {
            get {
                return ResourceManager.GetString("TagGroupIndexExample", resourceCulture);
            }
        }
        
        public static string TagMatchIndex {
            get {
                return ResourceManager.GetString("TagMatchIndex", resourceCulture);
            }
        }
        
        public static string TagMatchIndexDescription {
            get {
                return ResourceManager.GetString("TagMatchIndexDescription", resourceCulture);
            }
        }
        
        public static string TagMatchIndexExample {
            get {
                return ResourceManager.GetString("TagMatchIndexExample", resourceCulture);
            }
        }
        
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        public static string TMDB {
            get {
                return ResourceManager.GetString("TMDB", resourceCulture);
            }
        }
        
        public static string TmdbAPIDocumentationUri {
            get {
                return ResourceManager.GetString("TmdbAPIDocumentationUri", resourceCulture);
            }
        }
        
        public static string TmdbApiKeyWatermark {
            get {
                return ResourceManager.GetString("TmdbApiKeyWatermark", resourceCulture);
            }
        }
        
        public static string TMDBAttribution {
            get {
                return ResourceManager.GetString("TMDBAttribution", resourceCulture);
            }
        }
        
        public static string TMDBMatchSelect {
            get {
                return ResourceManager.GetString("TMDBMatchSelect", resourceCulture);
            }
        }
        
        public static string TMDBOptions {
            get {
                return ResourceManager.GetString("TMDBOptions", resourceCulture);
            }
        }
        
        public static string TMDBRenameMatchProviderDescription {
            get {
                return ResourceManager.GetString("TMDBRenameMatchProviderDescription", resourceCulture);
            }
        }
        
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string FunctionSeparateCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionSeparateCompactDefinition", resourceCulture);
            }
        }
        
        public static string FunctionSeparateCompactExample {
            get {
                return ResourceManager.GetString("FunctionSeparateCompactExample", resourceCulture);
            }
        }
        
        public static string FunctionSeparateDefinition {
            get {
                return ResourceManager.GetString("FunctionSeparateDefinition", resourceCulture);
            }
        }
        
        public static string FunctionSeparateDescription {
            get {
                return ResourceManager.GetString("FunctionSeparateDescription", resourceCulture);
            }
        }
        
        public static string FunctionSeparateExample {
            get {
                return ResourceManager.GetString("FunctionSeparateExample", resourceCulture);
            }
        }
        
        public static string FunctionSeparateParams {
            get {
                return ResourceManager.GetString("FunctionSeparateParams", resourceCulture);
            }
        }
    }
}
