//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarryFileMan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarryFileMan.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarryFileMan is a file manager with a primary focus of renaming and managing media files and folders..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarryFileMan.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/tm-barry/BarryFileMan.
        /// </summary>
        public static string AppUrl {
            get {
                return ResourceManager.GetString("AppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Path.
        /// </summary>
        public static string ConfigPath {
            get {
                return ResourceManager.GetString("ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy New.
        /// </summary>
        public static string CopyNew {
            get {
                return ResourceManager.GetString("CopyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Original.
        /// </summary>
        public static string CopyOriginal {
            get {
                return ResourceManager.GetString("CopyOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Load Option.
        /// </summary>
        public static string DefaultLoadOption {
            get {
                return ResourceManager.GetString("DefaultLoadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Regex File Filter.
        /// </summary>
        public static string DefaultRegexFileFilter {
            get {
                return ResourceManager.GetString("DefaultRegexFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Empty Folders.
        /// </summary>
        public static string DeleteEmptyFolders {
            get {
                return ResourceManager.GetString("DeleteEmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Empty Folders Default.
        /// </summary>
        public static string DeleteEmptyFoldersDefault {
            get {
                return ResourceManager.GetString("DeleteEmptyFoldersDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to indicate if folders that are empty after flattening should be deleted on save..
        /// </summary>
        public static string DeleteEmptyFoldersDescription {
            get {
                return ResourceManager.GetString("DeleteEmptyFoldersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Excluded Files.
        /// </summary>
        public static string DeleteExcludedFiles {
            get {
                return ResourceManager.GetString("DeleteExcludedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Excluded Files Default.
        /// </summary>
        public static string DeleteExcludedFilesDefault {
            get {
                return ResourceManager.GetString("DeleteExcludedFilesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to indicate if files marked excluded should be deleted on save..
        /// </summary>
        public static string DeleteExcludedFilesDescription {
            get {
                return ResourceManager.GetString("DeleteExcludedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Preset.
        /// </summary>
        public static string DeletePreset {
            get {
                return ResourceManager.GetString("DeletePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this preset?.
        /// </summary>
        public static string DeletePresetPrompt {
            get {
                return ResourceManager.GetString("DeletePresetPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Regular Expression Language Quick Reference.
        /// </summary>
        public static string DotNetRegexQuickReferenceTitle {
            get {
                return ResourceManager.GetString("DotNetRegexQuickReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-language-quick-reference.
        /// </summary>
        public static string DotNetRegexQuickReferenceUrl {
            get {
                return ResourceManager.GetString("DotNetRegexQuickReferenceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop Files or Folders.
        /// </summary>
        public static string DragDropFilesFolders {
            get {
                return ResourceManager.GetString("DragDropFilesFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string Episode {
            get {
                return ResourceManager.GetString("Episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete empty folders!
        ///{0}
        ///{1}.
        /// </summary>
        public static string FailedToDeleteEmptyFoldersMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteEmptyFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the following excluded files:
        ///{0}.
        /// </summary>
        public static string FailedToDeleteExcludedFilesMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteExcludedFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move the following files:
        ///{0}.
        /// </summary>
        public static string FailedToMoveFilesMessage {
            get {
                return ResourceManager.GetString("FailedToMoveFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename &amp; Directory.
        /// </summary>
        public static string FilenameAndDirectory {
            get {
                return ResourceManager.GetString("FilenameAndDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files failed to be renamed:
        ///
        ///{0}.
        /// </summary>
        public static string FilesFailedToRenameMessage {
            get {
                return ResourceManager.GetString("FilesFailedToRenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files successfully renamed!.
        /// </summary>
        public static string FilesRenamedSuccessMessage {
            get {
                return ResourceManager.GetString("FilesRenamedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Match.
        /// </summary>
        public static string FindMatch {
            get {
                return ResourceManager.GetString("FindMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten.
        /// </summary>
        public static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten Folder.
        /// </summary>
        public static string FlattenFolder {
            get {
                return ResourceManager.GetString("FlattenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to flatten the following folder?
        ///
        ///{0}.
        /// </summary>
        public static string FlattenFolderConfirmationQuestion {
            get {
                return ResourceManager.GetString("FlattenFolderConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to flatten....
        /// </summary>
        public static string FlattenFolderDialogWatermark {
            get {
                return ResourceManager.GetString("FlattenFolderDialogWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to flatten....
        /// </summary>
        public static string FlattenFolderPickerPlaceholder {
            get {
                return ResourceManager.GetString("FlattenFolderPickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder to Flatten.
        /// </summary>
        public static string FlattenFolderPickerTitle {
            get {
                return ResourceManager.GetString("FlattenFolderPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten Options.
        /// </summary>
        public static string FlattenOptions {
            get {
                return ResourceManager.GetString("FlattenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten a directory by moving all the files from subdirectories to the root directory..
        /// </summary>
        public static string FlattenPageDescription {
            get {
                return ResourceManager.GetString("FlattenPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a regex expression (default: &apos;.*&apos;).
        /// </summary>
        public static string FlattenRegexFileFilterWatermark {
            get {
                return ResourceManager.GetString("FlattenRegexFileFilterWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder successfully flattened!.
        /// </summary>
        public static string FolderFlattenedSuccessMessage {
            get {
                return ResourceManager.GetString("FolderFlattenedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ap( value ).
        /// </summary>
        public static string FunctionAppendCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionAppendCompactDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.ap(&apos; - end&apos;)&gt;.
        /// </summary>
        public static string FunctionAppendCompactExample {
            get {
                return ResourceManager.GetString("FunctionAppendCompactExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to append( value ).
        /// </summary>
        public static string FunctionAppendDefinition {
            get {
                return ResourceManager.GetString("FunctionAppendDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appends a string to the end of the tag..
        /// </summary>
        public static string FunctionAppendDescription {
            get {
                return ResourceManager.GetString("FunctionAppendDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.append(&apos; - end)&gt;.
        /// </summary>
        public static string FunctionAppendExample {
            get {
                return ResourceManager.GetString("FunctionAppendExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value - string to append.
        /// </summary>
        public static string FunctionAppendParams {
            get {
                return ResourceManager.GetString("FunctionAppendParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pd( type, char, length ).
        /// </summary>
        public static string FunctionPadCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionPadCompactDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.pd( l, &apos;0&apos;, 2 )&gt;.
        /// </summary>
        public static string FunctionPadCompactExample {
            get {
                return ResourceManager.GetString("FunctionPadCompactExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pad( type, char, length ).
        /// </summary>
        public static string FunctionPadDefinition {
            get {
                return ResourceManager.GetString("FunctionPadDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to pad a tag to a certain length, such as padding a number with leading 0s..
        /// </summary>
        public static string FunctionPadDescription {
            get {
                return ResourceManager.GetString("FunctionPadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.pad( left, &apos;0&apos;, 2 )&gt;.
        /// </summary>
        public static string FunctionPadExample {
            get {
                return ResourceManager.GetString("FunctionPadExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type     - left|l|right|r
        ///char     - pad character
        ///length  - pad to length.
        /// </summary>
        public static string FunctionPadParams {
            get {
                return ResourceManager.GetString("FunctionPadParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pp( value ).
        /// </summary>
        public static string FunctionPrependCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionPrependCompactDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.pp(&apos;start - &apos;)&gt;.
        /// </summary>
        public static string FunctionPrependCompactExample {
            get {
                return ResourceManager.GetString("FunctionPrependCompactExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prepend( value ).
        /// </summary>
        public static string FunctionPrependDefinition {
            get {
                return ResourceManager.GetString("FunctionPrependDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepends a string to the start of the tag..
        /// </summary>
        public static string FunctionPrependDescription {
            get {
                return ResourceManager.GetString("FunctionPrependDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.prepend(&apos;start - &apos;)&gt;.
        /// </summary>
        public static string FunctionPrependExample {
            get {
                return ResourceManager.GetString("FunctionPrependExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value - string to prepend.
        /// </summary>
        public static string FunctionPrependParams {
            get {
                return ResourceManager.GetString("FunctionPrependParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rp( input, replace ).
        /// </summary>
        public static string FunctionReplaceCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionReplaceCompactDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.rp( &apos;.&apos;, &apos; &apos; )&gt;.
        /// </summary>
        public static string FunctionReplaceCompactExample {
            get {
                return ResourceManager.GetString("FunctionReplaceCompactExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replace( input, replace ).
        /// </summary>
        public static string FunctionReplaceDefinition {
            get {
                return ResourceManager.GetString("FunctionReplaceDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to replace a string with another string..
        /// </summary>
        public static string FunctionReplaceDescription {
            get {
                return ResourceManager.GetString("FunctionReplaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.replace( &apos;.&apos;, &apos; &apos; )&gt;.
        /// </summary>
        public static string FunctionReplaceExample {
            get {
                return ResourceManager.GetString("FunctionReplaceExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input      - string to replace
        ///replace  - replace with.
        /// </summary>
        public static string FunctionReplaceParams {
            get {
                return ResourceManager.GetString("FunctionReplaceParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tm( type ).
        /// </summary>
        public static string FunctionTrimCompactDefinition {
            get {
                return ResourceManager.GetString("FunctionTrimCompactDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.tm()&gt;.
        /// </summary>
        public static string FunctionTrimCompactExample {
            get {
                return ResourceManager.GetString("FunctionTrimCompactExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trim( type ).
        /// </summary>
        public static string FunctionTrimDefinition {
            get {
                return ResourceManager.GetString("FunctionTrimDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to trim whitespace..
        /// </summary>
        public static string FunctionTrimDescription {
            get {
                return ResourceManager.GetString("FunctionTrimDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.trim( both )&gt;.
        /// </summary>
        public static string FunctionTrimExample {
            get {
                return ResourceManager.GetString("FunctionTrimExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type - left|l|right|r|both|b.
        /// </summary>
        public static string FunctionTrimParams {
            get {
                return ResourceManager.GetString("FunctionTrimParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename - Regex.
        /// </summary>
        public static string HelpRenameRegexTitle {
            get {
                return ResourceManager.GetString("HelpRenameRegexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Adult.
        /// </summary>
        public static string IncludeAdult {
            get {
                return ResourceManager.GetString("IncludeAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A string used to test out the current match/rename patterns..
        /// </summary>
        public static string InputDescription {
            get {
                return ResourceManager.GetString("InputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input/Output.
        /// </summary>
        public static string InputOutput {
            get {
                return ResourceManager.GetString("InputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Files.
        /// </summary>
        public static string LoadFiles {
            get {
                return ResourceManager.GetString("LoadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Folder.
        /// </summary>
        public static string LoadFolder {
            get {
                return ResourceManager.GetString("LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Groups.
        /// </summary>
        public static string MatchGroups {
            get {
                return ResourceManager.GetString("MatchGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the matches/groups of the current test string..
        /// </summary>
        public static string MatchGroupsDescription {
            get {
                return ResourceManager.GetString("MatchGroupsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Pattern.
        /// </summary>
        public static string MatchPattern {
            get {
                return ResourceManager.GetString("MatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression used to match data in the filename/directory. The regex group names are what can be used in the rename pattern tags. This uses .NET&apos;s regular expression syntax..
        /// </summary>
        public static string MatchPatternDescription {
            get {
                return ResourceManager.GetString("MatchPatternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Type.
        /// </summary>
        public static string MatchType {
            get {
                return ResourceManager.GetString("MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates what the match pattern should use to find matches.
        ///
        ///Filename - Match only the filename
        ///
        ///Filename &amp; Directory - Match the filename and parent directory
        ///
        ///Full Path - Match the full path of the file/directory.
        /// </summary>
        public static string MatchTypeDescription {
            get {
                return ResourceManager.GetString("MatchTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Names.
        /// </summary>
        public static string NewNames {
            get {
                return ResourceManager.GetString("NewNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Paths.
        /// </summary>
        public static string NewPaths {
            get {
                return ResourceManager.GetString("NewPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File(s) Found.
        /// </summary>
        public static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches Found.
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Files.
        /// </summary>
        public static string OriginalFiles {
            get {
                return ResourceManager.GetString("OriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Paths.
        /// </summary>
        public static string OriginalPaths {
            get {
                return ResourceManager.GetString("OriginalPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed test string result after applying the match/rename patterns..
        /// </summary>
        public static string OutputDescription {
            get {
                return ResourceManager.GetString("OutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Name.
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a preset with that name..
        /// </summary>
        public static string PresetNameAlreadyExistsError {
            get {
                return ResourceManager.GetString("PresetNameAlreadyExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The preset name cannot be an empty string..
        /// </summary>
        public static string PresetNameEmptyError {
            get {
                return ResourceManager.GetString("PresetNameEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the preset:.
        /// </summary>
        public static string PresetNamePrompt {
            get {
                return ResourceManager.GetString("PresetNamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex File Filter.
        /// </summary>
        public static string RegexFileFilter {
            get {
                return ResourceManager.GetString("RegexFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to filter down the list of files to those that match the entered regular expression..
        /// </summary>
        public static string RegexFileFilterDescription {
            get {
                return ResourceManager.GetString("RegexFileFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a regex expression (default: &apos;.*&apos;).
        /// </summary>
        public static string RegexFileFilterPlaceholder {
            get {
                return ResourceManager.GetString("RegexFileFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a user supplied regular expression to pull data/tags from the file/directory name..
        /// </summary>
        public static string RegexRenameMatchProviderDescription {
            get {
                return ResourceManager.GetString("RegexRenameMatchProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex Settings.
        /// </summary>
        public static string RegexSettings {
            get {
                return ResourceManager.GetString("RegexSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files will be renamed. Do you want to continue?.
        /// </summary>
        public static string RenameFilesSaveConfirmation {
            get {
                return ResourceManager.GetString("RenameFilesSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files have errors and can&apos;t be renamed. Do you still want to continue?.
        /// </summary>
        public static string RenameFilesSaveErrorsConfirmation {
            get {
                return ResourceManager.GetString("RenameFilesSaveErrorsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Match Providers.
        /// </summary>
        public static string RenameMatchProviders {
            get {
                return ResourceManager.GetString("RenameMatchProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files using various match providers..
        /// </summary>
        public static string RenamePageDescription {
            get {
                return ResourceManager.GetString("RenamePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Pattern.
        /// </summary>
        public static string RenamePattern {
            get {
                return ResourceManager.GetString("RenamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename pattern syntax used to rename the string. For the regex provider you can use the match pattern group names for the tags. See the main rename help page for a reference of the syntax..
        /// </summary>
        public static string RenamePatternDescription {
            get {
                return ResourceManager.GetString("RenamePatternDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Pattern Syntax.
        /// </summary>
        public static string RenamePatternSyntax {
            get {
                return ResourceManager.GetString("RenamePatternSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename pattern uses a custom syntax using tags enclosed in angle brackets &lt;&gt;.  Functions such as .pad, .replace, and .trim can also be used on each tag to further format data.  Free text can also be used outside of tags..
        /// </summary>
        public static string RenamePatternSyntaxDescription {
            get {
                return ResourceManager.GetString("RenamePatternSyntaxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename - Regex.
        /// </summary>
        public static string RenameRegexHelpTitle {
            get {
                return ResourceManager.GetString("RenameRegexHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode number of tv show episode..
        /// </summary>
        public static string RenameTMDBEpisodeDescription {
            get {
                return ResourceManager.GetString("RenameTMDBEpisodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename - TMDB.
        /// </summary>
        public static string RenameTMDBHelpTitle {
            get {
                return ResourceManager.GetString("RenameTMDBHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of movie/tv show..
        /// </summary>
        public static string RenameTMDBLanguageDescription {
            get {
                return ResourceManager.GetString("RenameTMDBLanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query used to find movie/tv show..
        /// </summary>
        public static string RenameTMDBQueryDescription {
            get {
                return ResourceManager.GetString("RenameTMDBQueryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season number of tv show episode..
        /// </summary>
        public static string RenameTMDBSeasonDescription {
            get {
                return ResourceManager.GetString("RenameTMDBSeasonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release/aired year of movie/tv show..
        /// </summary>
        public static string RenameTMDBYearDescription {
            get {
                return ResourceManager.GetString("RenameTMDBYearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to Default.
        /// </summary>
        public static string RevertToDefault {
            get {
                return ResourceManager.GetString("RevertToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will revert all settings to the application&apos;s defaults. Are you sure you want to continue?.
        /// </summary>
        public static string RevertToDefaultConfirmationMessage {
            get {
                return ResourceManager.GetString("RevertToDefaultConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong reverting to default settings..
        /// </summary>
        public static string RevertToDefaultErrorMessage {
            get {
                return ResourceManager.GetString("RevertToDefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the correct match:.
        /// </summary>
        public static string SelectCorrectMatchLabel {
            get {
                return ResourceManager.GetString("SelectCorrectMatchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Expanded Default.
        /// </summary>
        public static string SidebarExpandedDefault {
            get {
                return ResourceManager.GetString("SidebarExpandedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Fallback.
        /// </summary>
        public static string TagFallback {
            get {
                return ResourceManager.GetString("TagFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags can be given a fallback value for when a match is not found using ?? followed by the fallback string like shown below..
        /// </summary>
        public static string TagFallbackDescription {
            get {
                return ResourceManager.GetString("TagFallbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.replace(&apos;.&apos;,&apos; &apos;) ?? &apos;&apos;&gt;.
        /// </summary>
        public static string TagFallbackExample {
            get {
                return ResourceManager.GetString("TagFallbackExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Format Functions.
        /// </summary>
        public static string TagFormatFunctions {
            get {
                return ResourceManager.GetString("TagFormatFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag values can be formatted using various built in functions.  Functions can be specified after the tag name by a period, function name, and function parameters like shown below..
        /// </summary>
        public static string TagFormatFunctionsDescription {
            get {
                return ResourceManager.GetString("TagFormatFunctionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName.replace(&apos;.&apos;,&apos; &apos;)&gt;.
        /// </summary>
        public static string TagFormatFunctionsExample {
            get {
                return ResourceManager.GetString("TagFormatFunctionsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Group Index.
        /// </summary>
        public static string TagGroupIndex {
            get {
                return ResourceManager.GetString("TagGroupIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the case there are multiple instances of a group in a single match, you can specify which group to use by adding the group index number in square brackets after the tag name like shown below.  If specifying both a match and group index, the group index must come after the match index.  Group index is zero based, so the first group would be 0.  If no group index is specified it will default to the first group.  If you specify a -1 for the group index it will use the last group..
        /// </summary>
        public static string TagGroupIndexDescription {
            get {
                return ResourceManager.GetString("TagGroupIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName{2}[1]&gt;.
        /// </summary>
        public static string TagGroupIndexExample {
            get {
                return ResourceManager.GetString("TagGroupIndexExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Match Index.
        /// </summary>
        public static string TagMatchIndex {
            get {
                return ResourceManager.GetString("TagMatchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the case there are multiple matches for a file, you can specify which match to use by adding the match index number in curly brackets after the tag name like shown below.  Match index is zero based, so the first match would be 0.  If no match index is specified it will default to the first match.  If you specify a -1 for the match index it will use the last match..
        /// </summary>
        public static string TagMatchIndexDescription {
            get {
                return ResourceManager.GetString("TagMatchIndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tagName{2}&gt;.
        /// </summary>
        public static string TagMatchIndexExample {
            get {
                return ResourceManager.GetString("TagMatchIndexExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB.
        /// </summary>
        public static string TMDB {
            get {
                return ResourceManager.GetString("TMDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.themoviedb.org/docs/getting-started.
        /// </summary>
        public static string TmdbAPIDocumentationUri {
            get {
                return ResourceManager.GetString("TmdbAPIDocumentationUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.themoviedb.org/settings/api.
        /// </summary>
        public static string TmdbApiKeyWatermark {
            get {
                return ResourceManager.GetString("TmdbApiKeyWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses TMDB and the TMDB APIs but is not endorsed, certified, or otherwise approved by TMDB..
        /// </summary>
        public static string TMDBAttribution {
            get {
                return ResourceManager.GetString("TMDBAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB Match Select.
        /// </summary>
        public static string TMDBMatchSelect {
            get {
                return ResourceManager.GetString("TMDBMatchSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMDB Options.
        /// </summary>
        public static string TMDBOptions {
            get {
                return ResourceManager.GetString("TMDBOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses regex along with the TMDB API to match files to movies &amp; television shows.  A valid API key must be configured in the settings page for this provider to show up..
        /// </summary>
        public static string TMDBRenameMatchProviderDescription {
            get {
                return ResourceManager.GetString("TMDBRenameMatchProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
