//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarryFileMan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarryFileMan.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarryFileMan is a file manager with a primary focus of renaming and managing media files and folders..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarryFileMan.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/tm-barry/BarryFileMan.
        /// </summary>
        public static string AppUrl {
            get {
                return ResourceManager.GetString("AppUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy New.
        /// </summary>
        public static string CopyNew {
            get {
                return ResourceManager.GetString("CopyNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Original.
        /// </summary>
        public static string CopyOriginal {
            get {
                return ResourceManager.GetString("CopyOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Load Option.
        /// </summary>
        public static string DefaultLoadOption {
            get {
                return ResourceManager.GetString("DefaultLoadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Empty Folders.
        /// </summary>
        public static string DeleteEmptyFolders {
            get {
                return ResourceManager.GetString("DeleteEmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to indicate if folders that are empty after flattening should be deleted on save..
        /// </summary>
        public static string DeleteEmptyFoldersDescription {
            get {
                return ResourceManager.GetString("DeleteEmptyFoldersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Excluded Files.
        /// </summary>
        public static string DeleteExcludedFiles {
            get {
                return ResourceManager.GetString("DeleteExcludedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to indicate if files marked excluded should be deleted on save..
        /// </summary>
        public static string DeleteExcludedFilesDescription {
            get {
                return ResourceManager.GetString("DeleteExcludedFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and Drop Files or Folders.
        /// </summary>
        public static string DragDropFilesFolders {
            get {
                return ResourceManager.GetString("DragDropFilesFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded.
        /// </summary>
        public static string Excluded {
            get {
                return ResourceManager.GetString("Excluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete empty folders!
        ///{0}
        ///{1}.
        /// </summary>
        public static string FailedToDeleteEmptyFoldersMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteEmptyFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the following excluded files:
        ///{0}.
        /// </summary>
        public static string FailedToDeleteExcludedFilesMessage {
            get {
                return ResourceManager.GetString("FailedToDeleteExcludedFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move the following files:
        ///{0}.
        /// </summary>
        public static string FailedToMoveFilesMessage {
            get {
                return ResourceManager.GetString("FailedToMoveFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename &amp; Directory.
        /// </summary>
        public static string FilenameAndDirectory {
            get {
                return ResourceManager.GetString("FilenameAndDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files failed to be renamed:
        ///
        ///{0}.
        /// </summary>
        public static string FilesFailedToRenameMessage {
            get {
                return ResourceManager.GetString("FilesFailedToRenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files successfully renamed!.
        /// </summary>
        public static string FilesRenamedSuccessMessage {
            get {
                return ResourceManager.GetString("FilesRenamedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten.
        /// </summary>
        public static string Flatten {
            get {
                return ResourceManager.GetString("Flatten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten Folder.
        /// </summary>
        public static string FlattenFolder {
            get {
                return ResourceManager.GetString("FlattenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to flatten the following folder?
        ///
        ///{0}.
        /// </summary>
        public static string FlattenFolderConfirmationQuestion {
            get {
                return ResourceManager.GetString("FlattenFolderConfirmationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to flatten....
        /// </summary>
        public static string FlattenFolderPickerPlaceholder {
            get {
                return ResourceManager.GetString("FlattenFolderPickerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder to Flatten.
        /// </summary>
        public static string FlattenFolderPickerTitle {
            get {
                return ResourceManager.GetString("FlattenFolderPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten Options.
        /// </summary>
        public static string FlattenOptions {
            get {
                return ResourceManager.GetString("FlattenOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatten a directory by moving all the files from subdirectories to the root directory..
        /// </summary>
        public static string FlattenPageDescription {
            get {
                return ResourceManager.GetString("FlattenPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder successfully flattened!.
        /// </summary>
        public static string FolderFlattenedSuccessMessage {
            get {
                return ResourceManager.GetString("FolderFlattenedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Path.
        /// </summary>
        public static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename - Regex.
        /// </summary>
        public static string HelpRenameRegexTitle {
            get {
                return ResourceManager.GetString("HelpRenameRegexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Files.
        /// </summary>
        public static string LoadFiles {
            get {
                return ResourceManager.GetString("LoadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Folder.
        /// </summary>
        public static string LoadFolder {
            get {
                return ResourceManager.GetString("LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Groups.
        /// </summary>
        public static string MatchGroups {
            get {
                return ResourceManager.GetString("MatchGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Pattern.
        /// </summary>
        public static string MatchPattern {
            get {
                return ResourceManager.GetString("MatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Type.
        /// </summary>
        public static string MatchType {
            get {
                return ResourceManager.GetString("MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Names.
        /// </summary>
        public static string NewNames {
            get {
                return ResourceManager.GetString("NewNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Paths.
        /// </summary>
        public static string NewPaths {
            get {
                return ResourceManager.GetString("NewPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File(s) Found.
        /// </summary>
        public static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Matches Found.
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Files.
        /// </summary>
        public static string OriginalFiles {
            get {
                return ResourceManager.GetString("OriginalFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Paths.
        /// </summary>
        public static string OriginalPaths {
            get {
                return ResourceManager.GetString("OriginalPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex.
        /// </summary>
        public static string Regex {
            get {
                return ResourceManager.GetString("Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex File Filter.
        /// </summary>
        public static string RegexFileFilter {
            get {
                return ResourceManager.GetString("RegexFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to filter down the list of files to those that match the entered regular expression..
        /// </summary>
        public static string RegexFileFilterDescription {
            get {
                return ResourceManager.GetString("RegexFileFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a regex expression (default: &apos;.*&apos;).
        /// </summary>
        public static string RegexFileFilterPlaceholder {
            get {
                return ResourceManager.GetString("RegexFileFilterPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a user supplied regular expression to pull data/tags from the file/directory name..
        /// </summary>
        public static string RegexRenameMatchProviderDescription {
            get {
                return ResourceManager.GetString("RegexRenameMatchProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renamed String.
        /// </summary>
        public static string RenamedString {
            get {
                return ResourceManager.GetString("RenamedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files will be renamed. Do you want to continue?.
        /// </summary>
        public static string RenameFilesSaveConfirmation {
            get {
                return ResourceManager.GetString("RenameFilesSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files have errors and can&apos;t be renamed. Do you still want to continue?.
        /// </summary>
        public static string RenameFilesSaveErrorsConfirmation {
            get {
                return ResourceManager.GetString("RenameFilesSaveErrorsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Match Providers.
        /// </summary>
        public static string RenameMatchProviders {
            get {
                return ResourceManager.GetString("RenameMatchProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename files using various match providers..
        /// </summary>
        public static string RenamePageDescription {
            get {
                return ResourceManager.GetString("RenamePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Pattern.
        /// </summary>
        public static string RenamePattern {
            get {
                return ResourceManager.GetString("RenamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert to Default.
        /// </summary>
        public static string RevertToDefault {
            get {
                return ResourceManager.GetString("RevertToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will revert all settings to the application&apos;s defaults. Are you sure you want to continue?.
        /// </summary>
        public static string RevertToDefaultConfirmationMessage {
            get {
                return ResourceManager.GetString("RevertToDefaultConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong reverting to default settings..
        /// </summary>
        public static string RevertToDefaultErrorMessage {
            get {
                return ResourceManager.GetString("RevertToDefaultErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidebar Expanded Default.
        /// </summary>
        public static string SidebarExpandedDefault {
            get {
                return ResourceManager.GetString("SidebarExpandedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test String.
        /// </summary>
        public static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
